#                                    script BY HANI LAMANI (VEGETA-LFH)
#                                for contact FB : www.facebook.com/lamanihani
#                if you change the name of the author to your NAME , that dont make you the coder ok ;) 
#                                                    ...
#                                           TY FOR USE MY SCRIPT ^_^
#                           KEEP      THE          BEST         TO      THE       END
import os
import sys
import time
print('''
XX   MMMMMMMMMMMMMMMMss'''                          '''ssMMMMMMMMMMMMMMMM   XX
XX   MMMMMMMMMMMMyy''                                    ''yyMMMMMMMMMMMM   XX
XX   MMMMMMMMyy''                                            ''yyMMMMMMMM   XX
XX   MMMMMy''                                                    ''yMMMMM   XX
XX   MMMy'                                                          'yMMM   XX
XX   Mh'                                                              'hM   XX
XX   -                                                                  -   XX
XX                                                                          XX
XX   ::                                                                ::   XX
XX   MMhh.        ..hhhhhh..                      ..hhhhhh..        .hhMM   XX
XX   MMMMMh   ..hhMMMMMMMMMMhh.                .hhMMMMMMMMMMhh..   hMMMMM   XX
XX   ---MMM .hMMMMdd:::dMMMMMMMhh..        ..hhMMMMMMMd:::ddMMMMh. MMM---   XX
XX   MMMMMM MMmm''      'mmMMMMMMMMyy.  .yyMMMMMMMMmm'      ''mmMM MMMMMM   XX
XX   ---mMM ''             'mmMMMMMMMM  MMMMMMMMmm'             '' MMm---   XX
XX   yyyym'    .              'mMMMMm'  'mMMMMm'              .    'myyyy   XX
XX   mm''    .y'     ..yyyyy..  ''''      ''''  ..yyyyy..     'y.    ''mm   XX
XX           MN    .sMMMMMMMMMss.   .    .   .ssMMMMMMMMMs.    NM           XX
XX           N`    MMMMMMMMMMMMMN   M    M   NMMMMMMMMMMMMM    `N           XX
XX            +  .sMNNNNNMMMMMN+   `N    N`   +NMMMMMNNNNNMs.  +            XX
XX              o+++     ++++Mo    M      M    oM++++     +++o              XX
XX                                oo      oo                                XX
XX           oM                 oo          oo                 Mo           XX
XX         oMMo                M              M                oMMo         XX
XX       +MMMM                 s              s                 MMMM+       XX
XX      +MMMMM+            +++NNNN+        +NNNN+++            +MMMMM+      XX
XX     +MMMMMMM+       ++NNMMMMMMMMN+    +NMMMMMMMMNN++       +MMMMMMM+     XX
XX     MMMMMMMMMNN+++NNMMMMMMMMMMMMMMNNNNMMMMMMMMMMMMMMNN+++NNMMMMMMMMM     XX
XX     yMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy     XX
XX   m  yMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy  m   XX
XX   MMm yMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy mMM   XX
XX   MMMm .yyMMMMMMMMMMMMMMMM     MMMMMMMMMM     MMMMMMMMMMMMMMMMyy. mMMM   XX
XX   MMMMd   ''''hhhhh       odddo          obbbo        hhhh''''   dMMMM   XX
XX   MMMMMd             'hMMMMMMMMMMddddddMMMMMMMMMMh'             dMMMMM   XX
XX   MMMMMMd              'hMMMMMMMMMMMMMMMMMMMMMMh'              dMMMMMM   XX
XX   MMMMMMM-               ''ddMMMMMMMMMMMMMMdd''               -MMMMMMM   XX
XX   MMMMMMMM                   '::dddddddd::'                   MMMMMMMM   XX
XX   MMMMMMMM-                                                  -MMMMMMMM   XX
XX   MMMMMMMMM                                                  MMMMMMMMM   XX
XX   MMMMMMMMMy                                                yMMMMMMMMM   XX
XX   MMMMMMMMMMy.                                            .yMMMMMMMMMM   XX
XX   MMMMMMMMMMMMy.                                        .yMMMMMMMMMMMM   XX
XX   MMMMMMMMMMMMMMy.                                    .yMMMMMMMMMMMMMM   XX
XX   MMMMMMMMMMMMMMMMs.                                .sMMMMMMMMMMMMMMMM   XX
XX   MMMMMMMMMMMMMMMMMMss.           ....           .ssMMMMMMMMMMMMMMMMMM   XX
XX   MMMMMMMMMMMMMMMMMMMMNo         oNNNNo         oNMMMMMMMMMMMMMMMMMMMM   XX
''')
def slowprint(s):
    for c in s + '\n' :
        sys.stdout.write(c)
        sys.stdout.flush()
        time.sleep(10. / 100)
slowprint("[!] Starting : ")
time.sleep(5)
os.system('clear')

#the banner of the script 
print('''
\033[1;31m\033[91m _____   __  __      _      ___   _          _____ ___ _   _ ____  _____ ____  
\033[91m| ____| |  \/  |    / \    |_ _| | |        |  ___|_ _| \ | |  _ \| ____|  _ \ 
\033[91m|  _|   | |\/| |   / _ \    | |  | |   _____| |_   | ||  \| | | | |  _| | |_) |
\033[91m| |___  | |  | |  / ___ \   | |  | |__|_____|  _|  | || |\  | |_| | |___|  _ < 
\033[91m|_____| |_|  |_| /_/   \_\ |___| |_____|    |_|   |___|_| \_|____/|_____|_| \_\



\033[97m|+------------------------------------------+|
\033[97m|$Author :  \033[96mLamani Hani \033[91mVEGETA-LFH           \033[97m|
\033[97m|$Contact : \033[96mwww.facebook.com/lamanihani      \033[97m|
\033[97m|$Date : \033[96m19/08/2017                          \033[97m|
\033[97m|$TNX TO :      -Robert Willson-             |
\033[97m|+------------------------------------------+|
''')
print(" ")
print("\033[96m[!]\033[97mAnswer the following \033[91mquestions\033[97m ! :")
print(" ")
                                                                                                                                                                                                                               
asmi = input("\033[95m[?] \033[97menter the \033[91mVictim's name\033[97m :")
lakbi = input("\033[95m[?] \033[97menter the Victim's \033[91mfamily name \033[97m:")
datte = input("\033[95m[?] \033[97menter the \033[91myear of birth of the victime \033[97m:")
loveyou = input("\033[95m[?] \033[97menter the \033[91mnickname \033[97mof the victime \033[97m:")
farik = input("\033[95m[?] \033[97menter the \033[91mSport Team of the victime \033[97m:")
zyada = input("\033[95m[?] \033[97menter another thing about victime :")
print(" ")
print("\033[95m[!] \033[91mEMAILLIST \033[97mWAS CREATED")

a = (asmi+lakbi)
b = (asmi+"."+lakbi)
c = (asmi+lakbi+".")
d = (asmi+lakbi+"1")
e = (asmi+lakbi+"2")
f = (asmi+lakbi+"3")
g = (asmi+lakbi+"4")
h = (asmi+lakbi+"5")
i = (asmi+lakbi+"6")
j = (asmi+lakbi+"7")
k = (asmi+lakbi+"8")
l = (asmi+lakbi+"9")
m = (asmi+lakbi+"10")
n = (asmi+lakbi+"123")
o = (asmi+lakbi+"12")
p = (asmi+lakbi+"12345")
q = (asmi+lakbi+"0123")
r = (asmi+lakbi+"1234567890")
s = (asmi+lakbi+"0123456789")
t = (asmi+lakbi+"1234")
u = (asmi+lakbi+datte)
v = (asmi+datte)
w = (asmi+datte+".")
y = (asmi+"."+datte)
z = (asmi+loveyou)
aa = (asmi+loveyou)
bb = (asmi+loveyou+".")
cc = (asmi+"."+loveyou)
dd = (asmi+loveyou+"1")
ee = (asmi+loveyou+"2") 
ff = (asmi+loveyou+"3")
gg = (asmi+loveyou+"4")
hh = (asmi+loveyou+"5")
ii = (asmi+loveyou+"6")
jj = (asmi+loveyou+"7")
kk = (asmi+loveyou+"8")
ll = (asmi+loveyou+"9")
mm = (asmi+loveyou+"10")
nn = (asmi+loveyou+"123")
oo = (asmi+loveyou+"12345")
pp = (asmi+loveyou+"1234567890")
qq = (asmi+loveyou+"012")
rr = (asmi+loveyou+"0123")
ss = (asmi+loveyou+"012345")
tt = (asmi+loveyou+"0123456789")
uu = (asmi+loveyou+"01234567890")
vv = (asmi+"1"+lakbi)
ww = (asmi+"2"+lakbi)
yy = (asmi+"3"+lakbi)
zz = (asmi+"4"+lakbi)
aaa = (asmi+"5"+lakbi)
bbb = (asmi+"6"+lakbi)
ccc = (asmi+"7"+lakbi)
ddd = (asmi+"8"+lakbi)
eee = (asmi+"9"+lakbi)
fff = (asmi+"0"+lakbi)
ggg = (asmi+"123"+lakbi)
hhh = (asmi+"12345"+lakbi)
iii =  (asmi+loveyou+"0")
jjj = (asmi+lakbi+"0")
kkk = (asmi+"0"+loveyou)
lll = (asmi+"1"+loveyou)
mmm = (asmi+"2"+loveyou)
nnn = (asmi+"3"+loveyou)
ooo = (asmi+"4"+loveyou)
ppp = (asmi+"5"+loveyou)
qqq = (asmi+"6"+loveyou)
rrr = (asmi+"7"+loveyou)
sss = (asmi+"8"+loveyou)
ttt = (asmi+"9"+loveyou)
uuu = (asmi+"10"+loveyou)
vvv = (asmi+"123"+loveyou)
www = (asmi+"10"+lakbi)
yyy = (asmi+"1234"+loveyou)
zzz = (asmi+"12345"+loveyou)
aaaa = (asmi+farik+"1")
bbbb = (asmi+farik)
cccc = (asmi+"."+farik)
dddd = (asmi+farik+"2")
eeee = (asmi+farik+"3")
ffff = (asmi+farik+"4")
gggg = (asmi+farik+"5")
hhhh = (asmi+farik+"6")
iiii = (asmi+farik+"7") 
jjjj = (asmi+farik+"8") 
kkkk = (asmi+farik+"9") 
llll = (asmi+farik+"0")
mmmm = (asmi+farik+"10")
nnnn = (asmi+farik+"123")
oooo = (asmi+farik+"1234")
pppp = (asmi+farik+"12345")
qqqq = (asmi+farik+"01234") 
rrrr = (asmi+farik+"0123")
ssss = (asmi+farik+"123456789")
tttt = (asmi+farik+"12345678910")
uuuu = (asmi+farik+"0123456789")
vvvv = (asmi+farik+"012345678910")
wwww = (asmi+farik+".")
xxxx = (asmi+"1"+farik)
yyyy = (asmi+"2"+farik)
zzzz = (asmi+"3"+farik)
aaaaa = (asmi+"0"+farik)
bbbbb = (asmi+"4"+farik)
ccccc = (asmi+"5"+farik)
ddddd = (asmi+"6"+farik)
eeeee = (asmi+"7"+farik)
fffff = (asmi+"8"+farik)
ggggg = (asmi+"9"+farik)
hhhhh = (asmi+"10"+farik)
iiiii = (asmi+"0"+farik)
jjjjj = (asmi+"123"+farik)
kkkkk = (asmi+"1234"+farik)
lllll = (asmi+"12345"+farik)
mmmmm = (asmi+"0123"+farik)
nnnnn = (asmi+"012345"+farik)
ooooo = (asmi+"1234567890"+farik)
ppppp = (asmi+"123456789"+farik)
qqqqq = (asmi+"0123456789"+farik)
rrrrr = (asmi+"012345678910"+farik)
sssss = (asmi+","+farik)
ttttt = (asmi+"11"+farik)
uuuuu = (asmi+"100"+farik)
aaaas = (asmi+zyada+"1")
bbbbs = (asmi+zyada)
ccccs = (asmi+"."+zyada)
dddds = (asmi+zyada+"2")
eeees = (asmi+zyada+"3")
ffffs = (asmi+zyada+"4")
ggggs = (asmi+zyada+"5")
hhhhs = (asmi+zyada+"6")
iiiis = (asmi+zyada+"7") 
jjjjs = (asmi+zyada+"8") 
kkkks = (asmi+zyada+"9") 
lllls = (asmi+zyada+"0")
mmmms = (asmi+zyada+"10")
nnnns = (asmi+zyada+"123")
oooos = (asmi+zyada+"1234")
pppps = (asmi+zyada+"12345")
qqqqs= (asmi+zyada+"01234") 
rrrrs = (asmi+zyada+"0123")
sssss = (asmi+zyada+"123456789")
tttts = (asmi+zyada+"12345678910")
uuuus = (asmi+zyada+"0123456789")
vvvvs = (asmi+zyada+"012345678910")
wwwws = (asmi+zyada+".")
xxxxs = (asmi+"1"+zyada)
yyyys = (asmi+"2"+zyada)
zzzzs = (asmi+"3"+zyada)
aaaaas = (asmi+"0"+zyada)
bbbbbs = (asmi+"4"+zyada)
cccccs = (asmi+"5"+zyada)
ddddds = (asmi+"6"+zyada)
eeeees = (asmi+"7"+zyada)
fffffs = (asmi+"8"+zyada)
gggggs = (asmi+"9"+zyada)
hhhhhs = (asmi+"10"+zyada)
iiiiis = (asmi+"0"+zyada)
jjjjjs = (asmi+"123"+zyada)
kkkkks = (asmi+"1234"+zyada)
llllls = (asmi+"12345"+zyada)
mmmmms = (asmi+"0123"+zyada)
nnnnns = (asmi+"012345"+zyada)
ooooos = (asmi+"1234567890"+zyada)
ppppps = (asmi+"123456789"+zyada)
qqqqqs = (asmi+"0123456789"+zyada)
rrrrrs = (asmi+"012345678910"+zyada)
ssssss = (asmi+","+zyada)
ttttts = (asmi+"11"+zyada)
uuuuus = (asmi+"100"+zyada)




















al = (lakbi+asmi)
bl = (lakbi+"."+asmi)
cl = (lakbi+asmi+".")
dl = (lakbi+asmi+"1")
el = (lakbi+asmi+"2")
fl = (lakbi+asmi+"3")
gl = (lakbi+asmi+"4")
hl = (lakbi+asmi+"5")
il = (lakbi+asmi+"6")
jl = (lakbi+asmi+"7")
kl = (lakbi+asmi+"8")
ll = (lakbi+asmi+"9")
ml = (lakbi+asmi+"10")
nl = (lakbi+asmi+"123")
ol = (lakbi+asmi+"12")
pl= (lakbi+asmi+"12345")
ql = (lakbi+asmi+"0123")
rl = (lakbi+asmi+"1234567890")
sl = (lakbi+asmi+"0123456789")
tl = (lakbi+asmi+"1234")
ul = (lakbi+asmi+datte)
vl = (lakbi+datte)
wl = (lakbi+datte+".")
yl = (lakbi+"."+datte)
zl = (lakbi+loveyou)
aal = (lakbi+loveyou)
bbl = (lakbi+loveyou+".")
ccl = (lakbi+"."+loveyou)
ddl = (lakbi+loveyou+"1")
eel = (lakbi+loveyou+"2") 
ffl = (lakbi+loveyou+"3")
ggl = (lakbi+loveyou+"4")
hhl = (lakbi+loveyou+"5")
iil= (lakbi+loveyou+"6")
jjl= (lakbi+loveyou+"7")
kkl= (lakbi+loveyou+"8")
lll = (lakbi+loveyou+"9")
mml = (lakbi+loveyou+"10")
nnl = (lakbi+loveyou+"123")
ool = (lakbi+loveyou+"12345")
ppl = (lakbi+loveyou+"1234567890")
qql = (lakbi+loveyou+"012")
rrl = (lakbi+loveyou+"0123")
ssl = (lakbi+loveyou+"012345")
ttl = (lakbi+loveyou+"0123456789")
uul = (lakbi+loveyou+"01234567890")
vvl = (lakbi+"1"+asmi)
wwl = (lakbi+"2"+asmi)
yyl = (lakbi+"3"+asmi)
zzl = (lakbi+"4"+asmi)
aaal = (lakbi+"5"+asmi)
bbbl = (lakbi+"6"+asmi)
cccl = (lakbi+"7"+asmi)
dddl = (lakbi+"8"+asmi)
eeel = (lakbi+"9"+asmi)
fffl = (lakbi+"0"+asmi)
gggl = (lakbi+"123"+asmi)
hhhl = (lakbi+"12345"+asmi)
iiil =  (lakbi+loveyou+"0")
jjjl = (lakbi+lakbi+"0")
kkkl = (lakbi+"0"+loveyou)
llll = (lakbi+"1"+loveyou)
mmml = (lakbi+"2"+loveyou)
nnnl = (lakbi+"3"+loveyou)
oool = (lakbi+"4"+loveyou)
pppl = (lakbi+"5"+loveyou)
qqql = (lakbi+"6"+loveyou)
rrrl = (lakbi+"7"+loveyou)
sssl = (lakbi+"8"+loveyou)
tttl = (lakbi+"9"+loveyou)
uuul = (lakbi+"10"+loveyou)
vvvl = (lakbi+"123"+loveyou)
wwwl = (lakbi+"10"+asmi)
yyyl = (lakbi+"1234"+loveyou)
zzzl = (lakbi+"12345"+loveyou)
aaaal = (lakbi+farik+"1")
bbbbl = (lakbi+farik)
ccccl = (lakbi+"."+farik)
ddddl = (lakbi+farik+"2")
eeeel = (lakbi+farik+"3")
ffffl = (lakbi+farik+"4")
ggggl = (lakbi+farik+"5")
hhhhl = (lakbi+farik+"6")
iiiil = (lakbi+farik+"7") 
jjjjl = (lakbi+farik+"8") 
kkkkl = (lakbi+farik+"9") 
lllll = (lakbi+farik+"0")
mmmml = (lakbi+farik+"10")
nnnnl = (lakbi+farik+"123")
ooool = (lakbi+farik+"1234")
ppppl = (lakbi+farik+"12345")
qqqql = (lakbi+farik+"01234") 
rrrrl = (lakbi+farik+"0123")
ssssl = (lakbi+farik+"123456789")
ttttl = (lakbi+farik+"12345678910")
uuuul = (lakbi+farik+"0123456789")
vvvvl = (lakbi+farik+"012345678910")
wwwwl = (lakbi+farik+".")
xxxxl = (lakbi+"1"+farik)
yyyyl = (lakbi+"2"+farik)
zzzzl = (lakbi+"3"+farik)
aaaaal = (lakbi+"0"+farik)
bbbbbl = (lakbi+"4"+farik)
cccccl = (lakbi+"5"+farik)
dddddl = (lakbi+"6"+farik)
eeeeel = (lakbi+"7"+farik)
fffffl = (lakbi+"8"+farik)
gggggl = (lakbi+"9"+farik)
hhhhhl = (lakbi+"10"+farik)
iiiiil = (lakbi+"0"+farik)
jjjjjl = (lakbi+"123"+farik)
kkkkkl = (lakbi+"1234"+farik)
llllll = (lakbi+"12345"+farik)
mmmmml = (lakbi+"0123"+farik)
nnnnnl = (lakbi+"012345"+farik)
oooool = (lakbi+"1234567890"+farik)
pppppl = (lakbi+"123456789"+farik)
qqqqql = (lakbi+"0123456789"+farik)
rrrrrl = (lakbi+"012345678910"+farik)
sssssl = (lakbi+","+farik)
tttttl = (lakbi+"11"+farik)
uuuuul = (lakbi+"100"+farik)
aaaasl = (lakbi+zyada+"1")
bbbbsl = (lakbi+zyada)
ccccsl = (lakbi+"."+zyada)
ddddsl = (lakbi+zyada+"2")
eeeesl = (lakbi+zyada+"3")
ffffsl = (lakbi+zyada+"4")
ggggsl = (lakbi+zyada+"5")
hhhhsl = (lakbi+zyada+"6")
iiiisl = (lakbi+zyada+"7") 
jjjjsl = (lakbi+zyada+"8") 
kkkksl = (lakbi+zyada+"9") 
llllsl = (lakbi+zyada+"0")
mmmmsl = (lakbi+zyada+"10")
nnnnsl = (lakbi+zyada+"123")
oooosl = (lakbi+zyada+"1234")
ppppsl = (lakbi+zyada+"12345")
qqqqsl= (lakbi+zyada+"01234") 
rrrrsl = (lakbi+zyada+"0123")
sssssl = (lakbi+zyada+"123456789")
ttttsl = (lakbi+zyada+"12345678910")
uuuusl = (lakbi+zyada+"0123456789")
vvvvsl = (lakbi+zyada+"012345678910")
wwwwsl = (lakbi+zyada+".")
xxxxsl = (lakbi+"1"+zyada)
yyyysl = (lakbi+"2"+zyada)
zzzzsl = (lakbi+"3"+zyada)
aaaaasl = (lakbi+"0"+zyada)
bbbbbsl = (lakbi+"4"+zyada)
cccccsl = (lakbi+"5"+zyada)
dddddsl = (lakbi+"6"+zyada)
eeeeesl = (lakbi+"7"+zyada)
fffffsl = (lakbi+"8"+zyada)
gggggsl = (lakbi+"9"+zyada)
hhhhhsl = (lakbi+"10"+zyada)
iiiiisl = (lakbi+"0"+zyada)
jjjjjsl = (lakbi+"123"+zyada)
kkkkksl = (lakbi+"1234"+zyada)
lllllsl = (lakbi+"12345"+zyada)
mmmmmsl = (lakbi+"0123"+zyada)
nnnnnsl = (lakbi+"012345"+zyada)
ooooosl = (lakbi+"1234567890"+zyada)
pppppsl = (lakbi+"123456789"+zyada)
qqqqqsl = (lakbi+"0123456789"+zyada)
rrrrrsl = (lakbi+"012345678910"+zyada)
ssssssl = (lakbi+","+zyada)
tttttsl = (lakbi+"11"+zyada)
uuuuusl = (lakbi+"100"+zyada)








ak = (loveyou+lakbi)
bk = (loveyou+"."+lakbi)
ck = (loveyou+lakbi+".")
dk = (loveyou+lakbi+"1")
ek = (loveyou+lakbi+"2")
fk = (loveyou+lakbi+"3")
gk = (loveyou+lakbi+"4")
hk = (loveyou+lakbi+"5")
ik = (loveyou+lakbi+"6")
jk = (loveyou+lakbi+"7")
kk = (loveyou+lakbi+"8")
lk = (loveyou+lakbi+"9")
mk = (loveyou+lakbi+"10")
nk = (loveyou+lakbi+"123")
ok = (loveyou+lakbi+"12")
pk = (loveyou+lakbi+"12345")
qk = (loveyou+lakbi+"0123")
rk = (loveyou+lakbi+"1234567890")
sk = (loveyou+lakbi+"0123456789")
tk = (loveyou+lakbi+"1234")
uk = (loveyou+lakbi+datte)
vk = (loveyou+datte)
wk = (loveyou+datte+".")
yk = (loveyou+"."+datte)
zk = (loveyou+asmi)
aak = (loveyou+asmi)
bbk = (loveyou+asmi+".")
cck = (loveyou+"."+asmi)
ddk = (loveyou+asmi+"1")
eek = (loveyou+loveyou+"2") 
ffk = (loveyou+asmi+"3")
ggk = (loveyou+asmi+"4")
hhk = (loveyou+asmi+"5")
iik = (loveyou+asmi+"6")
jjk = (loveyou+asmi+"7")
kkk = (loveyou+asmi+"8")
llk = (loveyou+asmi+"9")
mmk = (loveyou+asmi+"10")
nnk = (loveyou+asmi+"123")
ook = (loveyou+asmi+"12345")
ppk = (loveyou+asmi+"1234567890")
qqk = (loveyou+asmi+"012")
rrk = (loveyou+asmi+"0123")
ssk = (loveyou+asmi+"012345")
ttk = (loveyou+asmi+"0123456789")
uuk = (loveyou+asmi+"01234567890")
vvk = (loveyou+"1"+lakbi)
wwk = (loveyou+"2"+lakbi)
yyk = (loveyou+"3"+lakbi)
zzk = (loveyou+"4"+lakbi)
aaak = (loveyou+"5"+lakbi)
bbbk = (loveyou+"6"+lakbi)
ccck = (loveyou+"7"+lakbi)
dddk = (loveyou+"8"+lakbi)
eeek = (loveyou+"9"+lakbi)
fffk = (loveyou+"0"+lakbi)
gggk = (loveyou+"123"+lakbi)
hhhk = (loveyou+"12345"+lakbi)
iiik =  (loveyou+asmi+"0")
jjjk = (loveyou+lakbi+"0")
kkkk = (loveyou+"0"+asmi)
lllk = (loveyou+"1"+loveyou)
mmmk = (loveyou+"2"+loveyou)
nnnk = (loveyou+"3"+asmi)
oook = (loveyou+"4"+asmi)
pppk = (loveyou+"5"+asmi)
qqqk = (loveyou+"6"+asmi)
rrrk = (loveyou+"7"+asmi)
sssk = (loveyou+"8"+asmi)
tttk = (loveyou+"9"+asmi)
uuuk = (loveyou+"10"+asmi)
vvvk = (loveyou+"123"+asmi)
wwwk = (loveyou+"10"+lakbi)
yyyk = (loveyou+"1234"+asmi)
zzzk = (loveyou+"12345"+asmi)
aaaak = (loveyou+farik+"1")
bbbbk = (loveyou+farik)
cccck = (loveyou+"."+farik)
ddddk = (loveyou+farik+"2")
eeeek = (loveyou+farik+"3")
ffffk = (loveyou+farik+"4")
ggggk = (loveyou+farik+"5")
hhhhk = (loveyou+farik+"6")
iiiik = (loveyou+farik+"7") 
jjjjk = (loveyou+farik+"8") 
kkkkk = (loveyou+farik+"9") 
llllk = (loveyou+farik+"0")
mmmmk = (loveyou+farik+"10")
nnnnk = (loveyou+farik+"123")
ooook = (loveyou+farik+"1234")
ppppk = (loveyou+farik+"12345")
qqqqk = (loveyou+farik+"01234") 
rrrrk = (loveyou+farik+"0123")
ssssk = (loveyou+farik+"123456789")
ttttk = (loveyou+farik+"12345678910")
uuuuk = (loveyou+farik+"0123456789")
vvvvk = (loveyou+farik+"012345678910")
wwwwk = (loveyou+farik+".")
xxxxk = (loveyou+"1"+farik)
yyyyk = (loveyou+"2"+farik)
zzzzk = (loveyou+"3"+farik)
aaaaak = (loveyou+"0"+farik)
bbbbbk = (loveyou+"4"+farik)
ccccck = (loveyou+"5"+farik)
dddddk = (loveyou+"6"+farik)
eeeeek = (loveyou+"7"+farik)
fffffk = (loveyou+"8"+farik)
gggggk = (loveyou+"9"+farik)
hhhhhk = (loveyou+"10"+farik)
iiiiik = (loveyou+"0"+farik)
jjjjjk = (loveyou+"123"+farik)
kkkkkk = (loveyou+"1234"+farik)
lllllk = (loveyou+"12345"+farik)
mmmmmk = (loveyou+"0123"+farik)
nnnnnk = (loveyou+"012345"+farik)
oooook = (loveyou+"1234567890"+farik)
pppppk = (loveyou+"123456789"+farik)
qqqqqk = (loveyou+"0123456789"+farik)
rrrrrk = (loveyou+"012345678910"+farik)
sssssk = (loveyou+","+farik)
tttttk = (loveyou+"11"+farik)
uuuuuk = (loveyou+"100"+farik)
aaaask = (loveyou+zyada+"1")
bbbbsk = (loveyou+zyada)
ccccsk = (loveyou+"."+zyada)
ddddsk = (loveyou+zyada+"2")
eeeesk = (loveyou+zyada+"3")
ffffsk = (loveyou+zyada+"4")
ggggsk = (loveyou+zyada+"5")
hhhhsk = (loveyou+zyada+"6")
iiiisk = (loveyou+zyada+"7") 
jjjjsk = (loveyou+zyada+"8") 
kkkksk = (loveyou+zyada+"9") 
llllsk = (loveyou+zyada+"0")
mmmmsk = (loveyou+zyada+"10")
nnnnsk = (loveyou+zyada+"123")
oooosk = (loveyou+zyada+"1234")
ppppsk = (loveyou+zyada+"12345")
qqqqsk=  (loveyou+zyada+"01234") 
rrrrsk = (loveyou+zyada+"0123")
sssssk = (loveyou+zyada+"123456789")
ttttsk = (loveyou+zyada+"12345678910")
uuuusk = (loveyou+zyada+"0123456789")
vvvvsk = (loveyou+zyada+"012345678910")
wwwwsk = (loveyou+zyada+".")
xxxxsk = (loveyou+"1"+zyada)
yyyysk = (loveyou+"2"+zyada)
zzzzsk = (loveyou+"3"+zyada)
aaaaask = (loveyou+"0"+zyada)
bbbbbsk = (loveyou+"4"+zyada)
cccccsk = (loveyou+"5"+zyada)
dddddsk = (loveyou+"6"+zyada)
eeeeesk = (loveyou+"7"+zyada)
fffffsk = (loveyou+"8"+zyada)
gggggsk = (loveyou+"9"+zyada)
hhhhhsk = (loveyou+"10"+zyada)
iiiiisk = (loveyou+"0"+zyada)
jjjjjsk = (loveyou+"123"+zyada)
kkkkksk = (loveyou+"1234"+zyada)
lllllsk = (loveyou+"12345"+zyada)
mmmmmsk = (loveyou+"0123"+zyada)
nnnnnsk = (loveyou+"012345"+zyada)
ooooosk = (loveyou+"1234567890"+zyada)
pppppsk = (loveyou+"123456789"+zyada)
qqqqqsk = (loveyou+"0123456789"+zyada)
rrrrrsk = (loveyou+"012345678910"+zyada)
ssssssk = (loveyou+","+zyada)
tttttsk = (loveyou+"11"+zyada)
uuuuusk = (loveyou+"100"+zyada)






akr = (zyada+lakbi)
bkr = (zyada+"."+lakbi)
ckr = (zyada+lakbi+".")
dkr = (zyada+lakbi+"1")
ekr = (zyada+lakbi+"2")
fkr = (zyada+lakbi+"3")
gkr = (zyada+lakbi+"4")
hkr = (zyada+lakbi+"5")
ikr = (zyada+lakbi+"6")
jkr = (zyada+lakbi+"7")
kkr = (zyada+lakbi+"8")
lkr = (zyada+lakbi+"9")
mkr = (zyada+lakbi+"10")
nkr = (zyada+lakbi+"123")
okr = (zyada+lakbi+"12")
pkr = (zyada+lakbi+"12345")
qkr = (zyada+lakbi+"0123")
rkr = (zyada+lakbi+"1234567890")
skr = (zyada+lakbi+"0123456789")
tkr = (zyada+lakbi+"1234")
ukr = (zyada+lakbi+datte)
vkr = (zyada+datte)
wkr = (zyada+datte+".")
ykr = (zyada+"."+datte)
zkr = (zyada+asmi)
aakr = (zyada+asmi)
bbkr = (zyada+asmi+".")
cckr = (zyada+"."+asmi)
ddkr = (zyada+asmi+"1")
eekr = (zyada+loveyou+"2") 
ffkr = (zyada+asmi+"3")
ggkr = (zyada+asmi+"4")
hhkr = (zyada+asmi+"5")
iikr = (zyada+asmi+"6")
jjkr = (zyada+asmi+"7")
kkkr = (zyada+asmi+"8")
llkr = (zyada+asmi+"9")
mmkr = (zyada+asmi+"10")
nnkr = (zyada+asmi+"123")
ookr = (zyada+asmi+"12345")
ppkr = (zyada+asmi+"1234567890")
qqkr = (zyada+asmi+"012")
rrkr = (zyada+asmi+"0123")
sskr = (zyada+asmi+"012345")
ttkr = (zyada+asmi+"0123456789")
uukr = (zyada+asmi+"01234567890")
vvkr = (zyada+"1"+lakbi)
wwkr = (zyada+"2"+lakbi)
yykr = (zyada+"3"+lakbi)
zzkr = (zyada+"4"+lakbi)
aaakr = (zyada+"5"+lakbi)
bbbkr = (zyada+"6"+lakbi)
ccckr = (zyada+"7"+lakbi)
dddkr = (zyada+"8"+lakbi)
eeekr = (zyada+"9"+lakbi)
fffkr = (zyada+"0"+lakbi)
gggkr = (zyada+"123"+lakbi)
hhhkr = (zyada+"12345"+lakbi)
iiikr = (zyada+asmi+"0")
jjjkr = (zyada+lakbi+"0")
kkkkr = (zyada+"0"+asmi)
lllkr = (zyada+"1"+loveyou)
mmmkr = (zyada+"2"+loveyou)
nnnkr = (zyada+"3"+asmi)
oookr = (zyada+"4"+asmi)
pppkr = (zyada+"5"+asmi)
qqqkr = (zyada+"6"+asmi)
rrrkr = (zyada+"7"+asmi)
ssskr = (zyada+"8"+asmi)
tttkr = (zyada+"9"+asmi)
uuukr = (zyada+"10"+asmi)
vvvkr = (zyada+"123"+asmi)
wwwkr = (zyada+"10"+lakbi)
yyykr = (zyada+"1234"+asmi)
zzzkr = (zyada+"12345"+asmi)
aaaakr = (zyada+farik+"1")
bbbbkr = (zyada+farik)
cccckr = (zyada+"."+farik)
ddddkr = (zyada+farik+"2")
eeeekr = (zyada+farik+"3")
ffffkr = (zyada+farik+"4")
ggggkr = (zyada+farik+"5")
hhhhkr = (zyada+farik+"6")
iiiikr = (zyada+farik+"7") 
jjjjkr = (zyada+farik+"8") 
kkkkkr = (zyada+farik+"9") 
llllkr = (zyada+farik+"0")
mmmmkr = (zyada+farik+"10")
nnnnkr = (zyada+farik+"123")
ooookr = (zyada+farik+"1234")
ppppkr = (zyada+farik+"12345")
qqqqkr = (zyada+farik+"01234") 
rrrrkr = (zyada+farik+"0123")
sssskr = (zyada+farik+"123456789")
ttttkr = (zyada+farik+"12345678910")
uuuukr = (zyada+farik+"0123456789")
vvvvkr = (zyada+farik+"012345678910")
wwwwkr = (zyada+farik+".")
xxxxkr = (zyada+"1"+farik)
yyyykr = (zyada+"2"+farik)
zzzzkr = (zyada+"3"+farik)
aaaaakr = (zyada+"0"+farik)
bbbbbkr = (zyada+"4"+farik)
ccccckr = (zyada+"5"+farik)
dddddkr = (zyada+"6"+farik)
eeeeekr = (zyada+"7"+farik)
fffffkr = (zyada+"8"+farik)
gggggkr = (zyada+"9"+farik)
hhhhhkr = (zyada+"10"+farik)
iiiiikr = (zyada+"0"+farik)
jjjjjkr = (zyada+"123"+farik)
kkkkkkr = (zyada+"1234"+farik)
lllllkr = (zyada+"12345"+farik)
mmmmmkr = (zyada+"0123"+farik)
nnnnnkr = (zyada+"012345"+farik)
oooookr = (zyada+"1234567890"+farik)
pppppkr = (zyada+"123456789"+farik)
qqqqqkr = (zyada+"0123456789"+farik)
rrrrrkr = (zyada+"012345678910"+farik)
ssssskr = (zyada+","+farik)
tttttkr = (zyada+"11"+farik)
uuuuukr = (zyada+"100"+farik)
aaaaskr = (zyada+loveyou+"1")
bbbbskr = (zyada+loveyou)
ccccskr = (zyada+"."+loveyou)
ddddskr = (zyada+loveyou+"2")
eeeeskr = (zyada+loveyou+"3")
ffffskr = (zyada+loveyou+"4")
ggggskr = (zyada+loveyou+"5")
hhhhskr = (zyada+loveyou+"6")
iiiiskr = (zyada+loveyou+"7") 
jjjjskr = (zyada+loveyou+"8") 
kkkkskr = (zyada+loveyou+"9") 
llllskr = (zyada+loveyou+"0")
mmmmskr = (zyada+loveyou+"10")
nnnnskr = (zyada+loveyou+"123")
ooooskr = (zyada+loveyou+"1234")
ppppskr = (zyada+loveyou+"12345")
qqqqskr=  (zyada+loveyou+"01234") 
rrrrskr = (zyada+loveyou+"0123")
ssssskr = (zyada+loveyou+"123456789")
ttttskr = (zyada+loveyou+"12345678910")
uuuuskr = (zyada+loveyou+"0123456789")
vvvvskr = (zyada+loveyou+"012345678910")
wwwwskr = (zyada+loveyou+".")
xxxxskr = (zyada+"1"+loveyou)
yyyyskr = (zyada+"2"+loveyou)
zzzzskr = (zyada+"3"+loveyou)
aaaaaskr = (zyada+"0"+loveyou)
bbbbbskr = (zyada+"4"+loveyou)
cccccskr = (zyada+"5"+loveyou)
dddddskr = (zyada+"6"+loveyou)
eeeeeskr = (zyada+"7"+loveyou)
fffffskr = (zyada+"8"+loveyou)
gggggskr = (zyada+"9"+loveyou)
hhhhhskr = (zyada+"10"+loveyou)
iiiiiskr = (zyada+"0"+loveyou)
jjjjjskr = (zyada+"123"+loveyou)
kkkkkskr = (zyada+"1234"+loveyou)
lllllskr = (zyada+"12345"+loveyou)
mmmmmskr = (zyada+"0123"+loveyou)
nnnnnskr = (zyada+"012345"+loveyou)
oooooskr = (zyada+"1234567890"+loveyou)
pppppskr = (zyada+"123456789"+loveyou)
qqqqqskr = (zyada+"0123456789"+loveyou)
rrrrrskr = (zyada+"012345678910"+loveyou)
sssssskr = (zyada+","+loveyou)
tttttskr = (zyada+"11"+loveyou)
uuuuuskr = (zyada+"100"+loveyou)











file = open("inputfile.txt","a")
file.write(a+"@gmail.com"+"\n")
file.write(b+"@gmail.com"+"\n")
file.write(c+"@gmail.com"+"\n")
file.write(d+"@gmail.com"+"\n")
file.write(e+"@gmail.com"+"\n")
file.write(f+"@gmail.com"+"\n")
file.write(g+"@gmail.com"+"\n")
file.write(h+"@gmail.com"+"\n")
file.write(j+"@gmail.com"+"\n")
file.write(k+"@gmail.com"+"\n")
file.write(l+"@gmail.com"+"\n")
file.write(m+"@gmail.com"+"\n")
file.write(n+"@gmail.com"+"\n")
file.write(o+"@gmail.com"+"\n")
file.write(p+"@gmail.com"+"\n")
file.write(q+"@gmail.com"+"\n")
file.write(r+"@gmail.com"+"\n")
file.write(s+"@gmail.com"+"\n")
file.write(t+"@gmail.com"+"\n")
file.write(u+"@gmail.com"+"\n")
file.write(v+"@gmail.com"+"\n")
file.write(w+"@gmail.com"+"\n")
file.write(y+"@gmail.com"+"\n")
file.write(z+"@gmail.com"+"\n")
file.write(aa+"@gmail.com"+"\n")
file.write(bb+"@gmail.com"+"\n")
file.write(cc+"@gmail.com"+"\n")
file.write(dd+"@gmail.com"+"\n")
file.write(ee+"@gmail.com"+"\n")
file.write(ff+"@gmail.com"+"\n")
file.write(gg+"@gmail.com"+"\n")
file.write(hh+"@gmail.com"+"\n")
file.write(ii+"@gmail.com"+"\n")
file.write(jj+"@gmail.com"+"\n")
file.write(kk+"@gmail.com"+"\n")
file.write(ll+"@gmail.com"+"\n")
file.write(mm+"@gmail.com"+"\n")
file.write(nn+"@gmail.com"+"\n")
file.write(oo+"@gmail.com"+"\n")
file.write(pp+"@gmail.com"+"\n")
file.write(qq+"@gmail.com"+"\n")
file.write(rr+"@gmail.com"+"\n")
file.write(ss+"@gmail.com"+"\n")
file.write(tt+"@gmail.com"+"\n")
file.write(uu+"@gmail.com"+"\n")
file.write(vv+"@gmail.com"+"\n")
file.write(ww+"@gmail.com"+"\n")
file.write(yy+"@gmail.com"+"\n")
file.write(zz+"@gmail.com"+"\n")
file.write(aaa+"@gmail.com"+"\n")
file.write(bbb+"@gmail.com"+"\n")
file.write(ccc+"@gmail.com"+"\n")
file.write(ddd+"@gmail.com"+"\n")
file.write(eee+"@gmail.com"+"\n")
file.write(fff+"@gmail.com"+"\n")
file.write(ggg+"@gmail.com"+"\n")
file.write(hhh+"@gmail.com"+"\n")
file.write(iii+"@gmail.com"+"\n")
file.write(jjj+"@gmail.com"+"\n")
file.write(kkk+"@gmail.com"+"\n")
file.write(lll+"@gmail.com"+"\n")
file.write(mmm+"@gmail.com"+"\n")
file.write(nnn+"@gmail.com"+"\n")
file.write(ooo+"@gmail.com"+"\n")
file.write(ppp+"@gmail.com"+"\n")
file.write(qqq+"@gmail.com"+"\n")
file.write(rrr+"@gmail.com"+"\n")
file.write(sss+"@gmail.com"+"\n")
file.write(ttt+"@gmail.com"+"\n")
file.write(uuu+"@gmail.com"+"\n")
file.write(vvv+"@gmail.com"+"\n")
file.write(www+"@gmail.com"+"\n")
file.write(yyy+"@gmail.com"+"\n")
file.write(zzz+"@gmail.com"+"\n")
file.write(aaaa+"@gmail.com"+"\n")
file.write(bbbb+"@gmail.com"+"\n")
file.write(cccc+"@gmail.com"+"\n")
file.write(dddd+"@gmail.com"+"\n")
file.write(eeee+"@gmail.com"+"\n")
file.write(ffff+"@gmail.com"+"\n")
file.write(gggg+"@gmail.com"+"\n")
file.write(hhhh+"@gmail.com"+"\n")
file.write(iiii+"@gmail.com"+"\n")
file.write(jjjj+"@gmail.com"+"\n")
file.write(kkkk+"@gmail.com"+"\n")
file.write(llll+"@gmail.com"+"\n")
file.write(mmmm+"@gmail.com"+"\n")
file.write(nnnn+"@gmail.com"+"\n")
file.write(oooo+"@gmail.com"+"\n")
file.write(pppp+"@gmail.com"+"\n")
file.write(qqqq+"@gmail.com"+"\n")
file.write(rrrr+"@gmail.com"+"\n")
file.write(ssss+"@gmail.com"+"\n")
file.write(tttt+"@gmail.com"+"\n")
file.write(uuuu+"@gmail.com"+"\n")
file.write(vvvv+"@gmail.com"+"\n")
file.write(wwww+"@gmail.com"+"\n")
file.write(xxxx+"@gmail.com"+"\n")
file.write(yyyy+"@gmail.com"+"\n")
file.write(zzzz+"@gmail.com"+"\n")
file.write(aaaaa+"@gmail.com"+"\n")
file.write(bbbbb+"@gmail.com"+"\n")
file.write(ccccc+"@gmail.com"+"\n")
file.write(ddddd+"@gmail.com"+"\n")
file.write(eeeee+"@gmail.com"+"\n")
file.write(fffff+"@gmail.com"+"\n")
file.write(ggggg+"@gmail.com"+"\n")
file.write(hhhhh+"@gmail.com"+"\n")
file.write(iiiii+"@gmail.com"+"\n")
file.write(jjjjj+"@gmail.com"+"\n")
file.write(kkkkk+"@gmail.com"+"\n")
file.write(lllll+"@gmail.com"+"\n")
file.write(mmmmm+"@gmail.com"+"\n")
file.write(nnnnn+"@gmail.com"+"\n")
file.write(ooooo+"@gmail.com"+"\n")
file.write(ppppp+"@gmail.com"+"\n")
file.write(qqqqq+"@gmail.com"+"\n")
file.write(rrrrr+"@gmail.com"+"\n")
file.write(sssss+"@gmail.com"+"\n")
file.write(ttttt+"@gmail.com"+"\n")
file.write(aaaas+"@gmail.com"+"\n")
file.write(bbbbs+"@gmail.com"+"\n")
file.write(ccccs+"@gmail.com"+"\n")
file.write(dddds+"@gmail.com"+"\n")
file.write(eeees+"@gmail.com"+"\n")
file.write(ffffs+"@gmail.com"+"\n")
file.write(ggggs+"@gmail.com"+"\n")
file.write(hhhhs+"@gmail.com"+"\n")
file.write(iiiis+"@gmail.com"+"\n")
file.write(jjjjs+"@gmail.com"+"\n")
file.write(kkkks+"@gmail.com"+"\n")
file.write(lllls+"@gmail.com"+"\n")
file.write(mmmms+"@gmail.com"+"\n")
file.write(nnnns+"@gmail.com"+"\n")
file.write(oooos+"@gmail.com"+"\n")
file.write(pppps+"@gmail.com"+"\n")
file.write(qqqqs+"@gmail.com"+"\n")
file.write(rrrrs+"@gmail.com"+"\n")
file.write(sssss+"@gmail.com"+"\n")
file.write(tttts+"@gmail.com"+"\n")
file.write(uuuus+"@gmail.com"+"\n")
file.write(vvvvs+"@gmail.com"+"\n")
file.write(wwwws+"@gmail.com"+"\n")
file.write(xxxxs+"@gmail.com"+"\n")
file.write(yyyys+"@gmail.com"+"\n")
file.write(zzzzs+"@gmail.com"+"\n")
file.write(aaaaas+"@gmail.com"+"\n")
file.write(bbbbbs+"@gmail.com"+"\n")
file.write(cccccs+"@gmail.com"+"\n")
file.write(ddddds+"@gmail.com"+"\n")
file.write(eeeees+"@gmail.com"+"\n")
file.write(fffffs+"@gmail.com"+"\n")
file.write(gggggs+"@gmail.com"+"\n")
file.write(hhhhhs+"@gmail.com"+"\n")
file.write(iiiiis+"@gmail.com"+"\n")
file.write(jjjjjs+"@gmail.com"+"\n")
file.write(kkkkks+"@gmail.com"+"\n")
file.write(llllls+"@gmail.com"+"\n")
file.write(mmmmms+"@gmail.com"+"\n")
file.write(nnnnns+"@gmail.com"+"\n")
file.write(ooooos+"@gmail.com"+"\n")
file.write(ppppps+"@gmail.com"+"\n")
file.write(qqqqqs+"@gmail.com"+"\n")
file.write(rrrrrs+"@gmail.com"+"\n")
file.write(ssssss+"@gmail.com"+"\n")
file.write(ttttts+"@gmail.com"+"\n")




file.write(al+"@gmail.com"+"\n")
file.write(bl+"@gmail.com"+"\n")
file.write(cl+"@gmail.com"+"\n")
file.write(dl+"@gmail.com"+"\n")
file.write(el+"@gmail.com"+"\n")
file.write(fl+"@gmail.com"+"\n")
file.write(gl+"@gmail.com"+"\n")
file.write(hl+"@gmail.com"+"\n")
file.write(jl+"@gmail.com"+"\n")
file.write(kl+"@gmail.com"+"\n")
file.write(ll+"@gmail.com"+"\n")
file.write(ml+"@gmail.com"+"\n")
file.write(nl+"@gmail.com"+"\n")
file.write(ol+"@gmail.com"+"\n")
file.write(pl+"@gmail.com"+"\n")
file.write(ql+"@gmail.com"+"\n")
file.write(rl+"@gmail.com"+"\n")
file.write(sl+"@gmail.com"+"\n")
file.write(tl+"@gmail.com"+"\n")
file.write(ul+"@gmail.com"+"\n")
file.write(vl+"@gmail.com"+"\n")
file.write(wl+"@gmail.com"+"\n")
file.write(yl+"@gmail.com"+"\n")
file.write(zl+"@gmail.com"+"\n")
file.write(aal+"@gmail.com"+"\n")
file.write(bbl+"@gmail.com"+"\n")
file.write(ccl+"@gmail.com"+"\n")
file.write(ddl+"@gmail.com"+"\n")
file.write(eel+"@gmail.com"+"\n")
file.write(ffl+"@gmail.com"+"\n")
file.write(ggl+"@gmail.com"+"\n")
file.write(hhl+"@gmail.com"+"\n")
file.write(iil+"@gmail.com"+"\n")
file.write(jjl+"@gmail.com"+"\n")
file.write(kkl+"@gmail.com"+"\n")
file.write(lll+"@gmail.com"+"\n")
file.write(mml+"@gmail.com"+"\n")
file.write(nnl+"@gmail.com"+"\n")
file.write(ool+"@gmail.com"+"\n")
file.write(ppl+"@gmail.com"+"\n")
file.write(qql+"@gmail.com"+"\n")
file.write(rrl+"@gmail.com"+"\n")
file.write(ssl+"@gmail.com"+"\n")
file.write(ttl+"@gmail.com"+"\n")
file.write(uul+"@gmail.com"+"\n")
file.write(vvl+"@gmail.com"+"\n")
file.write(wwl+"@gmail.com"+"\n")
file.write(yyl+"@gmail.com"+"\n")
file.write(zzl+"@gmail.com"+"\n")
file.write(aaal+"@gmail.com"+"\n")
file.write(bbbl+"@gmail.com"+"\n")
file.write(cccl+"@gmail.com"+"\n")
file.write(dddl+"@gmail.com"+"\n")
file.write(eeel+"@gmail.com"+"\n")
file.write(fffl+"@gmail.com"+"\n")
file.write(gggl+"@gmail.com"+"\n")
file.write(hhhl+"@gmail.com"+"\n")
file.write(iiil+"@gmail.com"+"\n")
file.write(jjjl+"@gmail.com"+"\n")
file.write(kkkl+"@gmail.com"+"\n")
file.write(llll+"@gmail.com"+"\n")
file.write(mmml+"@gmail.com"+"\n")
file.write(nnnl+"@gmail.com"+"\n")
file.write(oool+"@gmail.com"+"\n")
file.write(pppl+"@gmail.com"+"\n")
file.write(qqql+"@gmail.com"+"\n")
file.write(rrrl+"@gmail.com"+"\n")
file.write(sssl+"@gmail.com"+"\n")
file.write(tttl+"@gmail.com"+"\n")
file.write(uuul+"@gmail.com"+"\n")
file.write(vvvl+"@gmail.com"+"\n")
file.write(wwwl+"@gmail.com"+"\n")
file.write(yyyl+"@gmail.com"+"\n")
file.write(zzzl+"@gmail.com"+"\n")
file.write(aaaal+"@gmail.com"+"\n")
file.write(bbbbl+"@gmail.com"+"\n")
file.write(ccccl+"@gmail.com"+"\n")
file.write(ddddl+"@gmail.com"+"\n")
file.write(eeeel+"@gmail.com"+"\n")
file.write(ffffl+"@gmail.com"+"\n")
file.write(ggggl+"@gmail.com"+"\n")
file.write(hhhhl+"@gmail.com"+"\n")
file.write(iiiil+"@gmail.com"+"\n")
file.write(jjjjl+"@gmail.com"+"\n")
file.write(kkkkl+"@gmail.com"+"\n")
file.write(lllll+"@gmail.com"+"\n")
file.write(mmmml+"@gmail.com"+"\n")
file.write(nnnnl+"@gmail.com"+"\n")
file.write(ooool+"@gmail.com"+"\n")
file.write(ppppl+"@gmail.com"+"\n")
file.write(qqqql+"@gmail.com"+"\n")
file.write(rrrrl+"@gmail.com"+"\n")
file.write(ssssl+"@gmail.com"+"\n")
file.write(ttttl+"@gmail.com"+"\n")
file.write(uuuul+"@gmail.com"+"\n")
file.write(vvvvl+"@gmail.com"+"\n")
file.write(wwwwl+"@gmail.com"+"\n")
file.write(xxxxl+"@gmail.com"+"\n")
file.write(yyyyl+"@gmail.com"+"\n")
file.write(zzzzl+"@gmail.com"+"\n")
file.write(aaaaal+"@gmail.com"+"\n")
file.write(bbbbbl+"@gmail.com"+"\n")
file.write(cccccl+"@gmail.com"+"\n")
file.write(dddddl+"@gmail.com"+"\n")
file.write(eeeeel+"@gmail.com"+"\n")
file.write(fffffl+"@gmail.com"+"\n")
file.write(gggggl+"@gmail.com"+"\n")
file.write(hhhhhl+"@gmail.com"+"\n")
file.write(iiiiil+"@gmail.com"+"\n")
file.write(jjjjjl+"@gmail.com"+"\n")
file.write(kkkkkl+"@gmail.com"+"\n")
file.write(llllll+"@gmail.com"+"\n")
file.write(mmmmml+"@gmail.com"+"\n")
file.write(nnnnnl+"@gmail.com"+"\n")
file.write(oooool+"@gmail.com"+"\n")
file.write(pppppl+"@gmail.com"+"\n")
file.write(qqqqql+"@gmail.com"+"\n")
file.write(rrrrrl+"@gmail.com"+"\n")
file.write(sssssl+"@gmail.com"+"\n")
file.write(tttttl+"@gmail.com"+"\n")
file.write(aaaasl+"@gmail.com"+"\n")
file.write(bbbbsl+"@gmail.com"+"\n")
file.write(ccccsl+"@gmail.com"+"\n")
file.write(ddddsl+"@gmail.com"+"\n")
file.write(eeeesl+"@gmail.com"+"\n")
file.write(ffffsl+"@gmail.com"+"\n")
file.write(ggggsl+"@gmail.com"+"\n")
file.write(hhhhsl+"@gmail.com"+"\n")
file.write(iiiisl+"@gmail.com"+"\n")
file.write(jjjjsl+"@gmail.com"+"\n")
file.write(kkkksl+"@gmail.com"+"\n")
file.write(llllsl+"@gmail.com"+"\n")
file.write(mmmmsl+"@gmail.com"+"\n")
file.write(nnnnsl+"@gmail.com"+"\n")
file.write(oooosl+"@gmail.com"+"\n")
file.write(ppppsl+"@gmail.com"+"\n")
file.write(qqqqsl+"@gmail.com"+"\n")
file.write(rrrrsl+"@gmail.com"+"\n")
file.write(sssssl+"@gmail.com"+"\n")
file.write(ttttsl+"@gmail.com"+"\n")
file.write(uuuusl+"@gmail.com"+"\n")
file.write(vvvvsl+"@gmail.com"+"\n")
file.write(wwwwsl+"@gmail.com"+"\n")
file.write(xxxxsl+"@gmail.com"+"\n")
file.write(yyyysl+"@gmail.com"+"\n")
file.write(zzzzsl+"@gmail.com"+"\n")
file.write(aaaaasl+"@gmail.com"+"\n")
file.write(bbbbbsl+"@gmail.com"+"\n")
file.write(cccccsl+"@gmail.com"+"\n")
file.write(dddddsl+"@gmail.com"+"\n")
file.write(eeeeesl+"@gmail.com"+"\n")
file.write(fffffsl+"@gmail.com"+"\n")
file.write(gggggsl+"@gmail.com"+"\n")
file.write(hhhhhsl+"@gmail.com"+"\n")
file.write(iiiiisl+"@gmail.com"+"\n")
file.write(jjjjjsl+"@gmail.com"+"\n")
file.write(kkkkksl+"@gmail.com"+"\n")
file.write(lllllsl+"@gmail.com"+"\n")
file.write(mmmmmsl+"@gmail.com"+"\n")
file.write(nnnnnsl+"@gmail.com"+"\n")
file.write(ooooosl+"@gmail.com"+"\n")
file.write(pppppsl+"@gmail.com"+"\n")
file.write(qqqqqsl+"@gmail.com"+"\n")
file.write(rrrrrsl+"@gmail.com"+"\n")
file.write(ssssssl+"@gmail.com"+"\n")
file.write(tttttsl+"@gmail.com"+"\n")





file.write(ak+"@gmail.com"+"\n")
file.write(bk+"@gmail.com"+"\n")
file.write(ck+"@gmail.com"+"\n")
file.write(dk+"@gmail.com"+"\n")
file.write(ek+"@gmail.com"+"\n")
file.write(fk+"@gmail.com"+"\n")
file.write(gk+"@gmail.com"+"\n")
file.write(hk+"@gmail.com"+"\n")
file.write(jk+"@gmail.com"+"\n")
file.write(kk+"@gmail.com"+"\n")
file.write(lk+"@gmail.com"+"\n")
file.write(mk+"@gmail.com"+"\n")
file.write(nk+"@gmail.com"+"\n")
file.write(ok+"@gmail.com"+"\n")
file.write(pk+"@gmail.com"+"\n")
file.write(qk+"@gmail.com"+"\n")
file.write(rk+"@gmail.com"+"\n")
file.write(sk+"@gmail.com"+"\n")
file.write(tk+"@gmail.com"+"\n")
file.write(uk+"@gmail.com"+"\n")
file.write(vk+"@gmail.com"+"\n")
file.write(wk+"@gmail.com"+"\n")
file.write(yk+"@gmail.com"+"\n")
file.write(zk+"@gmail.com"+"\n")
file.write(aak+"@gmail.com"+"\n")
file.write(bbk+"@gmail.com"+"\n")
file.write(cck+"@gmail.com"+"\n")
file.write(ddk+"@gmail.com"+"\n")
file.write(eek+"@gmail.com"+"\n")
file.write(ffk+"@gmail.com"+"\n")
file.write(ggk+"@gmail.com"+"\n")
file.write(hhk+"@gmail.com"+"\n")
file.write(iik+"@gmail.com"+"\n")
file.write(jjk+"@gmail.com"+"\n")
file.write(kkk+"@gmail.com"+"\n")
file.write(llk+"@gmail.com"+"\n")
file.write(mmk+"@gmail.com"+"\n")
file.write(nnk+"@gmail.com"+"\n")
file.write(ook+"@gmail.com"+"\n")
file.write(ppk+"@gmail.com"+"\n")
file.write(qqk+"@gmail.com"+"\n")
file.write(rrk+"@gmail.com"+"\n")
file.write(ssk+"@gmail.com"+"\n")
file.write(ttk+"@gmail.com"+"\n")
file.write(uuk+"@gmail.com"+"\n")
file.write(vvk+"@gmail.com"+"\n")
file.write(wwk+"@gmail.com"+"\n")
file.write(yyk+"@gmail.com"+"\n")
file.write(zzk+"@gmail.com"+"\n")
file.write(aaak+"@gmail.com"+"\n")
file.write(bbbk+"@gmail.com"+"\n")
file.write(ccck+"@gmail.com"+"\n")
file.write(dddk+"@gmail.com"+"\n")
file.write(eeek+"@gmail.com"+"\n")
file.write(fffk+"@gmail.com"+"\n")
file.write(gggk+"@gmail.com"+"\n")
file.write(hhhk+"@gmail.com"+"\n")
file.write(iiik+"@gmail.com"+"\n")
file.write(jjjk+"@gmail.com"+"\n")
file.write(kkkk+"@gmail.com"+"\n")
file.write(lllk+"@gmail.com"+"\n")
file.write(mmmk+"@gmail.com"+"\n")
file.write(nnnk+"@gmail.com"+"\n")
file.write(oook+"@gmail.com"+"\n")
file.write(pppk+"@gmail.com"+"\n")
file.write(qqqk+"@gmail.com"+"\n")
file.write(rrrk+"@gmail.com"+"\n")
file.write(sssk+"@gmail.com"+"\n")
file.write(tttk+"@gmail.com"+"\n")
file.write(uuuk+"@gmail.com"+"\n")
file.write(vvvk+"@gmail.com"+"\n")
file.write(wwwk+"@gmail.com"+"\n")
file.write(yyyk+"@gmail.com"+"\n")
file.write(zzzk+"@gmail.com"+"\n")
file.write(aaaak+"@gmail.com"+"\n")
file.write(bbbbk+"@gmail.com"+"\n")
file.write(cccck+"@gmail.com"+"\n")
file.write(ddddk+"@gmail.com"+"\n")
file.write(eeeek+"@gmail.com"+"\n")
file.write(ffffk+"@gmail.com"+"\n")
file.write(ggggk+"@gmail.com"+"\n")
file.write(hhhhk+"@gmail.com"+"\n")
file.write(iiiik+"@gmail.com"+"\n")
file.write(jjjjk+"@gmail.com"+"\n")
file.write(kkkkk+"@gmail.com"+"\n")
file.write(llllk+"@gmail.com"+"\n")
file.write(mmmmk+"@gmail.com"+"\n")
file.write(nnnnk+"@gmail.com"+"\n")
file.write(ooook+"@gmail.com"+"\n")
file.write(ppppk+"@gmail.com"+"\n")
file.write(qqqqk+"@gmail.com"+"\n")
file.write(rrrrk+"@gmail.com"+"\n")
file.write(ssssk+"@gmail.com"+"\n")
file.write(ttttk+"@gmail.com"+"\n")
file.write(uuuuk+"@gmail.com"+"\n")
file.write(vvvvk+"@gmail.com"+"\n")
file.write(wwwwk+"@gmail.com"+"\n")
file.write(xxxxk+"@gmail.com"+"\n")
file.write(yyyyk+"@gmail.com"+"\n")
file.write(zzzzk+"@gmail.com"+"\n")
file.write(aaaaak+"@gmail.com"+"\n")
file.write(bbbbbk+"@gmail.com"+"\n")
file.write(ccccck+"@gmail.com"+"\n")
file.write(dddddk+"@gmail.com"+"\n")
file.write(eeeeek+"@gmail.com"+"\n")
file.write(fffffk+"@gmail.com"+"\n")
file.write(gggggk+"@gmail.com"+"\n")
file.write(hhhhhk+"@gmail.com"+"\n")
file.write(iiiiik+"@gmail.com"+"\n")
file.write(jjjjjk+"@gmail.com"+"\n")
file.write(kkkkkk+"@gmail.com"+"\n")
file.write(lllllk+"@gmail.com"+"\n")
file.write(mmmmmk+"@gmail.com"+"\n")
file.write(nnnnnk+"@gmail.com"+"\n")
file.write(oooook+"@gmail.com"+"\n")
file.write(pppppk+"@gmail.com"+"\n")
file.write(qqqqqk+"@gmail.com"+"\n")
file.write(rrrrrk+"@gmail.com"+"\n")
file.write(sssssk+"@gmail.com"+"\n")
file.write(tttttk+"@gmail.com"+"\n")
file.write(aaaask+"@gmail.com"+"\n")
file.write(bbbbsk+"@gmail.com"+"\n")
file.write(ccccsk+"@gmail.com"+"\n")
file.write(ddddsk+"@gmail.com"+"\n")
file.write(eeeesk+"@gmail.com"+"\n")
file.write(ffffsk+"@gmail.com"+"\n")
file.write(ggggsk+"@gmail.com"+"\n")
file.write(hhhhsk+"@gmail.com"+"\n")
file.write(iiiisk+"@gmail.com"+"\n")
file.write(jjjjsk+"@gmail.com"+"\n")
file.write(kkkksk+"@gmail.com"+"\n")
file.write(llllsk+"@gmail.com"+"\n")
file.write(mmmmsk+"@gmail.com"+"\n")
file.write(nnnnsk+"@gmail.com"+"\n")
file.write(oooosk+"@gmail.com"+"\n")
file.write(ppppsk+"@gmail.com"+"\n")
file.write(qqqqsk+"@gmail.com"+"\n")
file.write(rrrrsk+"@gmail.com"+"\n")
file.write(sssssk+"@gmail.com"+"\n")
file.write(ttttsk+"@gmail.com"+"\n")
file.write(uuuusk+"@gmail.com"+"\n")
file.write(vvvvsk+"@gmail.com"+"\n")
file.write(wwwwsk+"@gmail.com"+"\n")
file.write(xxxxsk+"@gmail.com"+"\n")
file.write(yyyysk+"@gmail.com"+"\n")
file.write(zzzzsk+"@gmail.com"+"\n")
file.write(aaaaask+"@gmail.com"+"\n")
file.write(bbbbbsk+"@gmail.com"+"\n")
file.write(cccccsk+"@gmail.com"+"\n")
file.write(dddddsk+"@gmail.com"+"\n")
file.write(eeeeesk+"@gmail.com"+"\n")
file.write(fffffsk+"@gmail.com"+"\n")
file.write(gggggsk+"@gmail.com"+"\n")
file.write(hhhhhsk+"@gmail.com"+"\n")
file.write(iiiiisk+"@gmail.com"+"\n")
file.write(jjjjjsk+"@gmail.com"+"\n")
file.write(kkkkksk+"@gmail.com"+"\n")
file.write(lllllsk+"@gmail.com"+"\n")
file.write(mmmmmsk+"@gmail.com"+"\n")
file.write(nnnnnsk+"@gmail.com"+"\n")
file.write(ooooosk+"@gmail.com"+"\n")
file.write(pppppsk+"@gmail.com"+"\n")
file.write(qqqqqsk+"@gmail.com"+"\n")
file.write(rrrrrsk+"@gmail.com"+"\n")
file.write(ssssssk+"@gmail.com"+"\n")
file.write(tttttsk+"@gmail.com"+"\n")

















file.write(akr+"@gmail.com"+"\n")
file.write(bkr+"@gmail.com"+"\n")
file.write(ckr+"@gmail.com"+"\n")
file.write(dkr+"@gmail.com"+"\n")
file.write(ekr+"@gmail.com"+"\n")
file.write(fkr+"@gmail.com"+"\n")
file.write(gkr+"@gmail.com"+"\n")
file.write(hkr+"@gmail.com"+"\n")
file.write(jkr+"@gmail.com"+"\n")
file.write(kkr+"@gmail.com"+"\n")
file.write(lkr+"@gmail.com"+"\n")
file.write(mkr+"@gmail.com"+"\n")
file.write(nkr+"@gmail.com"+"\n")
file.write(okr+"@gmail.com"+"\n")
file.write(pkr+"@gmail.com"+"\n")
file.write(qkr+"@gmail.com"+"\n")
file.write(rkr+"@gmail.com"+"\n")
file.write(skr+"@gmail.com"+"\n")
file.write(tkr+"@gmail.com"+"\n")
file.write(ukr+"@gmail.com"+"\n")
file.write(vkr+"@gmail.com"+"\n")
file.write(wkr+"@gmail.com"+"\n")
file.write(ykr+"@gmail.com"+"\n")
file.write(zkr+"@gmail.com"+"\n")
file.write(aakr+"@gmail.com"+"\n")
file.write(bbkr+"@gmail.com"+"\n")
file.write(cckr+"@gmail.com"+"\n")
file.write(ddkr+"@gmail.com"+"\n")
file.write(eekr+"@gmail.com"+"\n")
file.write(ffkr+"@gmail.com"+"\n")
file.write(ggkr+"@gmail.com"+"\n")
file.write(hhkr+"@gmail.com"+"\n")
file.write(iikr+"@gmail.com"+"\n")
file.write(jjkr+"@gmail.com"+"\n")
file.write(kkkr+"@gmail.com"+"\n")
file.write(llkr+"@gmail.com"+"\n")
file.write(mmkr+"@gmail.com"+"\n")
file.write(nnkr+"@gmail.com"+"\n")
file.write(ookr+"@gmail.com"+"\n")
file.write(ppkr+"@gmail.com"+"\n")
file.write(qqkr+"@gmail.com"+"\n")
file.write(rrkr+"@gmail.com"+"\n")
file.write(sskr+"@gmail.com"+"\n")
file.write(ttkr+"@gmail.com"+"\n")
file.write(uukr+"@gmail.com"+"\n")
file.write(vvkr+"@gmail.com"+"\n")
file.write(wwkr+"@gmail.com"+"\n")
file.write(yykr+"@gmail.com"+"\n")
file.write(zzkr+"@gmail.com"+"\n")
file.write(aaakr+"@gmail.com"+"\n")
file.write(bbbkr+"@gmail.com"+"\n")
file.write(ccckr+"@gmail.com"+"\n")
file.write(dddkr+"@gmail.com"+"\n")
file.write(eeekr+"@gmail.com"+"\n")
file.write(fffkr+"@gmail.com"+"\n")
file.write(gggkr+"@gmail.com"+"\n")
file.write(hhhkr+"@gmail.com"+"\n")
file.write(iiikr+"@gmail.com"+"\n")
file.write(jjjkr+"@gmail.com"+"\n")
file.write(kkkkr+"@gmail.com"+"\n")
file.write(lllkr+"@gmail.com"+"\n")
file.write(mmmkr+"@gmail.com"+"\n")
file.write(nnnkr+"@gmail.com"+"\n")
file.write(oookr+"@gmail.com"+"\n")
file.write(pppkr+"@gmail.com"+"\n")
file.write(qqqkr+"@gmail.com"+"\n")
file.write(rrrkr+"@gmail.com"+"\n")
file.write(ssskr+"@gmail.com"+"\n")
file.write(tttkr+"@gmail.com"+"\n")
file.write(uuukr+"@gmail.com"+"\n")
file.write(vvvkr+"@gmail.com"+"\n")
file.write(wwwkr+"@gmail.com"+"\n")
file.write(yyykr+"@gmail.com"+"\n")
file.write(zzzkr+"@gmail.com"+"\n")
file.write(aaaakr+"@gmail.com"+"\n")
file.write(bbbbkr+"@gmail.com"+"\n")
file.write(cccckr+"@gmail.com"+"\n")
file.write(ddddkr+"@gmail.com"+"\n")
file.write(eeeekr+"@gmail.com"+"\n")
file.write(ffffkr+"@gmail.com"+"\n")
file.write(ggggkr+"@gmail.com"+"\n")
file.write(hhhhkr+"@gmail.com"+"\n")
file.write(iiiikr+"@gmail.com"+"\n")
file.write(jjjjkr+"@gmail.com"+"\n")
file.write(kkkkkr+"@gmail.com"+"\n")
file.write(llllkr+"@gmail.com"+"\n")
file.write(mmmmkr+"@gmail.com"+"\n")
file.write(nnnnkr+"@gmail.com"+"\n")
file.write(ooookr+"@gmail.com"+"\n")
file.write(ppppkr+"@gmail.com"+"\n")
file.write(qqqqkr+"@gmail.com"+"\n")
file.write(rrrrkr+"@gmail.com"+"\n")
file.write(sssskr+"@gmail.com"+"\n")
file.write(ttttkr+"@gmail.com"+"\n")
file.write(uuuukr+"@gmail.com"+"\n")
file.write(vvvvkr+"@gmail.com"+"\n")
file.write(wwwwkr+"@gmail.com"+"\n")
file.write(xxxxkr+"@gmail.com"+"\n")
file.write(yyyykr+"@gmail.com"+"\n")
file.write(zzzzkr+"@gmail.com"+"\n")
file.write(aaaaakr+"@gmail.com"+"\n")
file.write(bbbbbkr+"@gmail.com"+"\n")
file.write(ccccckr+"@gmail.com"+"\n")
file.write(dddddkr+"@gmail.com"+"\n")
file.write(eeeeekr+"@gmail.com"+"\n")
file.write(fffffkr+"@gmail.com"+"\n")
file.write(gggggkr+"@gmail.com"+"\n")
file.write(hhhhhkr+"@gmail.com"+"\n")
file.write(iiiiikr+"@gmail.com"+"\n")
file.write(jjjjjkr+"@gmail.com"+"\n")
file.write(kkkkkkr+"@gmail.com"+"\n")
file.write(lllllkr+"@gmail.com"+"\n")
file.write(mmmmmkr+"@gmail.com"+"\n")
file.write(nnnnnkr+"@gmail.com"+"\n")
file.write(oooookr+"@gmail.com"+"\n")
file.write(pppppkr+"@gmail.com"+"\n")
file.write(qqqqqkr+"@gmail.com"+"\n")
file.write(rrrrrkr+"@gmail.com"+"\n")
file.write(ssssskr+"@gmail.com"+"\n")
file.write(tttttkr+"@gmail.com"+"\n")
file.write(aaaaskr+"@gmail.com"+"\n")
file.write(bbbbskr+"@gmail.com"+"\n")
file.write(ccccskr+"@gmail.com"+"\n")
file.write(ddddskr+"@gmail.com"+"\n")
file.write(eeeeskr+"@gmail.com"+"\n")
file.write(ffffskr+"@gmail.com"+"\n")
file.write(ggggskr+"@gmail.com"+"\n")
file.write(hhhhskr+"@gmail.com"+"\n")
file.write(iiiiskr+"@gmail.com"+"\n")
file.write(jjjjskr+"@gmail.com"+"\n")
file.write(kkkkskr+"@gmail.com"+"\n")
file.write(llllskr+"@gmail.com"+"\n")
file.write(mmmmskr+"@gmail.com"+"\n")
file.write(nnnnskr+"@gmail.com"+"\n")
file.write(ooooskr+"@gmail.com"+"\n")
file.write(ppppskr+"@gmail.com"+"\n")
file.write(qqqqskr+"@gmail.com"+"\n")
file.write(rrrrskr+"@gmail.com"+"\n")
file.write(ssssskr+"@gmail.com"+"\n")
file.write(ttttskr+"@gmail.com"+"\n")
file.write(uuuuskr+"@gmail.com"+"\n")
file.write(vvvvskr+"@gmail.com"+"\n")
file.write(wwwwskr+"@gmail.com"+"\n")
file.write(xxxxskr+"@gmail.com"+"\n")
file.write(yyyyskr+"@gmail.com"+"\n")
file.write(zzzzskr+"@gmail.com"+"\n")
file.write(aaaaaskr+"@gmail.com"+"\n")
file.write(bbbbbskr+"@gmail.com"+"\n")
file.write(cccccskr+"@gmail.com"+"\n")
file.write(dddddskr+"@gmail.com"+"\n")
file.write(eeeeeskr+"@gmail.com"+"\n")
file.write(fffffskr+"@gmail.com"+"\n")
file.write(gggggskr+"@gmail.com"+"\n")
file.write(hhhhhskr+"@gmail.com"+"\n")
file.write(iiiiiskr+"@gmail.com"+"\n")
file.write(jjjjjskr+"@gmail.com"+"\n")
file.write(kkkkkskr+"@gmail.com"+"\n")
file.write(lllllskr+"@gmail.com"+"\n")
file.write(mmmmmskr+"@gmail.com"+"\n")
file.write(nnnnnskr+"@gmail.com"+"\n")
file.write(oooooskr+"@gmail.com"+"\n")
file.write(pppppskr+"@gmail.com"+"\n")
file.write(qqqqqskr+"@gmail.com"+"\n")
file.write(rrrrrskr+"@gmail.com"+"\n")
file.write(sssssskr+"@gmail.com"+"\n")
file.write(tttttskr+"@gmail.com"+"\n")








print(" ")
print("\033[95m[!] \033[97mstart \033[91mEMAIL_VALIDATION\033[97m: ")
print(" ")
print("\033[95m[*] \033[97mLeave the \033[91mscript \033[97mTo finish his work ,He will write the email in a text file")
print("\033[95m[*] \033[97mif the \033[96memail is \033[92mcorrect,\033[97mhe will write inside : \033[92mvictim-email.txt\033[97m ")
print(" ")
lotfiss = input("\033[95m[!]\033[97meverything is ready , press \033[91mENTER \033[97mto start.")
print("\033[95m[!] \033[91mstart :\033[97m")
os.system('pip install validate_email')
os.system('python request.py inputfile.txt')
print(" ")
os.remove('inputfile.txt')
print("\033[95m[*] \033[97mthe \033[91mscript \033[97mwas finished his work ,the emails was writed in a text file")
print("\033[95m[*]\033[97mthe \033[92mvictime email  \033[97mwas writed\033[97m inside : \033[92mvictime-email.txt\033[97m ")

  
